name: Generate and Deploy Javadoc

on:
  pull_request:
    types: [closed]
    branches:
      - main
permissions:
  contents: write

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and generate Javadoc
        run: |
          mvn -B javadoc:javadoc

      - name: Deploy Javadoc to GitHub Pages
        if: github.event.pull_request.merged == true
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/apidocs
          branch: gh-pages
