name: Generate Documentation

on:
  pull_request:
    types: [closed]
    branches:
      - main
permissions:
  contents: write

jobs:
  generate-doc:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Generer du Javadoc
        run: mvn -B javadoc:javadoc

      - name: Deploy to GitHub
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs