name: Generate and Deploy Javadoc

on:
  pull_request:
    types: [closed]  # Se déclenche lorsque la PR est fermée
    branches:
      - main  # Remplacez par la branche où vous souhaitez déployer

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest  # Exécute le job sur Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Récupère le code source

      - name: Set up JDK
        uses: actions/setup-java@v3  # Installe le JDK
        with:
          java-version: '11'  # Spécifiez la version de Java (adaptez si nécessaire)

      - name: Build and generate Javadoc
        run: |
          mvn -B javadoc:javadoc  # Exécute la commande Maven pour générer la documentation

      - name: Deploy Javadoc to GitHub Pages
        if: github.event.pull_request.merged == true  # Vérifie que la PR a été fusionnée
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Utilise un token GitHub pour l'authentification
          publish_dir: target/site/apidocs  # Répertoire où se trouve la documentation générée
          branch: gh-pages  # Spécifie la branche `gh-pages` pour le déploiement
